name: tudo_client
description: A simple to-do app
version: 1.0.0
homepage: https://github.com/cachapa/tudo_client

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^5.0.0

  hive_crdt: ^1.0.3
  http: ^0.13.1
  web_socket_channel: ^2.0.0

  clipboard: ^0.1.2+8
  flutter_barcode_scanner: ^2.0.0-nullsafety.0
  implicitly_animated_reorderable_list: ^0.4.0-dev+1
  path_provider: ^2.0.1
  qr_flutter: ^4.0.0
  share: ^2.0.0
  uni_links2: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: WaitingfortheSunrise
      fonts:
        - asset: assets/fonts/WaitingfortheSunrise-Regular.ttf
