name: tudo
description: A simple to-do app
version: 2.0.0
homepage: https://github.com/cachapa/tudo
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  hive: ^2.2.3
  http: ^0.13.6
  web_socket_channel: ^2.4.0

#  go_router: ^6.5.6
  rxdart: ^0.27.7
  sqlite_crdt: ^1.0.1
  # Required for Android and iOS because UPSERTs are only supported on very recent OS versions
  sqlite3_flutter_libs: ^0.5.13

  animated_list_plus: ^0.5.0
  clipboard: ^0.1.3
  device_info_plus: ^8.2.2
  mobile_scanner: ^3.2.0

  in_app_update: ^4.0.1
  package_info_plus: ^3.1.2
  platform_info: ^3.2.0
  path_provider: ^2.0.14
  qr_flutter: ^4.0.0
  share_plus: ^6.3.4
  uni_links: ^0.5.1
  uuid: ^3.0.7
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  flutter_lints: any

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
