name: tudo_server
description: Server counterpart to the tudo app
version: 1.0.0
homepage: https://github.com/cachapa/tudo

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  args: ^2.4.1
  http: ^0.13.6
  postgres_crdt: ^1.0.1
  rxdart: ^0.27.7
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_web_socket: ^1.0.4
  web_socket_channel: ^2.4.0
  version: ^3.0.2

dev_dependencies:
  lints: any
  test: any
